const fs=require('fs');const edit=(p,fn)=>fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));
edit('backend/routes/v1/index.js',s=>s.replace(/const savedDesignsStore = new Map\(\);[\s\S]*?\/\* ── 6\./,"router.use('/designs', require('../designRoutes'));\n\n/* ── 6.").replace(/router.post\('\/returns',[\s\S]*?\n\}\);/,"router.post('/returns', protect, (req,res)=>res.status(503).json({success:false,message:'Return requests are not enabled. Please contact store support.'}));"));
edit('frontend/services/api.ts',s=>s.replace('export const api = {',`export const api = {
  saveDesign: (payload:any) => fetchJSON<any>('/designs',{method:'POST',body:JSON.stringify(payload)}),
  getDesigns: () => fetchJSON<{designs:any[]}>('/designs'),`));
edit('frontend/app/shop/page.tsx',s=>s.replace("import { INITIAL_PRODUCTS } from '@/lib/productsData';","import {useCatalog} from '@/lib/useCatalog';").replace('  const [filterDrawerOpen','  const {products,loading,error}=useCatalog();\n  const [filterDrawerOpen').replace('INITIAL_PRODUCTS.filter','products.filter').replace('[searchQuery, filters]','[searchQuery, filters, products]').replace('{/* 1. Header', '{loading && <p role="status">Loading collection…</p>}{error && <p role="alert">Catalog unavailable: {error}</p>}\n      {/* 1. Header'));
edit('frontend/app/product/[slug]/page.tsx',s=>s.replace("import { INITIAL_PRODUCTS } from '@/lib/productsData';","import {useCatalog} from '@/lib/useCatalog';").replace("const product = INITIAL_PRODUCTS.find((p) => p.slug === slug) || INITIAL_PRODUCTS[0];","const {products,loading,error}=useCatalog();\n  const product=products.find(p=>p.slug===slug);\n  if(loading)return <p className=\"p-12\">Loading product…</p>;\n  if(!product)return <p className=\"p-12\">{error || 'Product not found.'} <Link href=\"/shop\">Back to shop</Link></p>;").replace('INITIAL_PRODUCTS.filter','products.filter'));
edit('frontend/app/bespoke/page.tsx',s=>s.replace("import { VoiceButton }", "import {SavedLooks} from '@/components/bespoke/SavedLooks';\nimport { VoiceButton }").replace('BESPOKE DESIGN ATELIER','YOUR CHARACTER. YOUR FIT.').replace('{/* Main 2-Column', '<SavedLooks />\n      {/* Main 2-Column'));
edit('frontend/app/visualizer/page.tsx',s=>s.replace("import { BMIRadialGauge }", "import {AvatarViewer} from '@/components/bespoke/AvatarViewer';\nimport { BMIRadialGauge }").replace('<BMIRadialGauge />','<div className="h-[620px]"><AvatarViewer /></div>\n            <p className="text-xs text-gray-500">Measurement-based illustration. Real-person photo try-on is available on the Try-On page; accuracy depends on the image and provider.</p>\n            <BMIRadialGauge />'));
edit('frontend/components/common/Header.tsx',s=>s.replace("{ label: '3D STUDIO', href: '/bespoke'", "{ label: 'CHARACTER LAB', href: '/studio'"));
edit('backend/controllers/authController.js',s=>s.replace('    const existingUser =',"    if (typeof password !== 'string' || password.length < 10 || password.length > 72) return res.status(400).json({message:'Password must be 10–72 characters.'});\n    const existingUser ="));
edit('frontend/store/fitStore.ts',s=>s.replace('confidenceScore: 92','confidenceScore: 0').replace('verifiedByUser: true,\n\n  setMeasurement','verifiedByUser: false,\n\n  setMeasurement'));
edit('.gitignore',s=>s+'\n.next/\n*.tsbuildinfo\n.expo/\nbackend/uploads/*\n!backend/uploads/.gitkeep\n');
