const fs=require('fs');const edit=(p,fn)=>fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));
edit('frontend/app/admin/page.tsx',s=>s.replace('/api/admin/dashboard','/api/admin/metrics').replace('</div>)}</>:<button','</div>)}</>}</>:<button'));
edit('frontend/app/layout.tsx',s=>s.replace("import { Header }", "import {SessionRestore} from '@/components/auth/SessionRestore';\nimport { Header }").replace('<Header />','<SessionRestore />\n        <Header />'));
edit('frontend/components/auth/LoginModal.tsx',s=>s.replace('<div className="mt-6 pt-4', '<a className="block mt-4 text-center text-sm underline" href="/register" onClick={closeLoginModal}>Create an account with email</a>\n          <div className="mt-6 pt-4').replace('Biometric privacy encrypted • No third-party data broker sharing','Your measurements remain linked to your account'));
edit('frontend/app/account/page.tsx',s=>s.replace("openLoginModal('otp')","openLoginModal('email')").replace('AUTHENTICATE WITH PHONE OTP','SIGN IN'));
edit('backend/config/db.js',s=>s.replace(/    console.warn\(`[\s\S]*?mode\. Backend API will still serve requests\.'\);/,"    throw new Error('MongoDB connection failed. Check MONGODB_URI and database availability.');"));
edit('backend/server.js',s=>s.replace(/\n\}\);\s*$/,"\n}).catch(() => {console.error('API startup failed: database connection unavailable. Check backend configuration.');process.exitCode=1;});\n"));
edit('frontend/services/api.ts',s=>s.replace('body: JSON.stringify(payload)\n  }),\n\n  getTryOnStatus',"body: JSON.stringify({modelImageBase64:payload.userImage,garmentImageUrl:payload.garmentImage,garmentType:payload.garmentType})\n  }),\n\n  getTryOnStatus"));
edit('frontend/components/tryon/TryOnViewer.tsx',s=>s.replace("import { api }", "import {useCatalog} from '@/lib/useCatalog';\nimport { api }").replace('  const [photo,',"  const {products}=useCatalog();\n  const [selectedGarment,setSelectedGarment]=useState('');\n  const [consent,setConsent]=useState(false);\n  const streamRef=useRef<MediaStream | null>(null);\n  useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop());},[]);\n  const [photo,").replace('      if (videoRef.current) {','      streamRef.current=stream;\n      if (videoRef.current) {').replace('    if (!file) return;',"    if (!file) return;\n    if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size>8*1024*1024){setProviderNotice('Choose a JPG, PNG or WebP under 8 MB.');return;}").replace('    if (!photo) return;',"    if (!photo || !selectedGarment || !consent) {setProviderNotice('Choose a garment and consent to photo processing first.');return;}").replace("        garmentType: 'top'","        garmentImage: products.find(p=>p.id===selectedGarment)?.images[0],\n        garmentType: products.find(p=>p.id===selectedGarment)?.category==='Bottoms'?'bottom':'top'").replace("server/.env","backend/.env").replace('      if (task.taskId) {\n        const res = await api.getTryOnStatus(task.taskId);\n        if (res.resultImageUrl) {\n          setResultPhoto(res.resultImageUrl);\n        }\n      }',`      if(task.taskId){
        for(let attempt=0;attempt<30;attempt++){
          const result=await api.getTryOnStatus(task.taskId);
          if(result.resultImageUrl){setResultPhoto(result.resultImageUrl);return;}
          if(result.status==='failed')throw new Error('Try-on generation failed.');
          await new Promise(resolve=>setTimeout(resolve,2000));
        }
        setProviderNotice('Generation is taking longer than expected. Please retry later.');
      }`));
edit('frontend/components/tryon/TryOnViewer.tsx',s=>s.replace(/(return \(\s*<div[^>]*>)/,'$1\n      <div className="p-4 bg-white rounded-xl space-y-3"><label className="block text-sm">Garment<select className="block border p-2 rounded-lg w-full" value={selectedGarment} onChange={e=>setSelectedGarment(e.target.value)}><option value="">Choose from the catalog</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="flex gap-2 text-xs"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} />I consent to sending this photo to the configured try-on provider. I have permission to use this photo.</label></div>'));
