const fs = require('fs');
const edit = (p, fn) => fs.writeFileSync(p, fn(fs.readFileSync(p, 'utf8')));
edit('package.json', s => { const p = JSON.parse(s); p.scripts = {start:'npm --prefix backend start', seed:'npm --prefix backend run seed', backend:'npm --prefix backend run dev', frontend:'npm --prefix frontend run dev', 'web':'npm --prefix frontend run dev','web:build':'npm --prefix frontend run build', mobile:'npm --prefix mobile-app start', test:'npm --prefix backend test', typecheck:'npm --prefix frontend run typecheck'}; return JSON.stringify(p,null,2); });
edit('frontend/package.json', s => {const p=JSON.parse(s);p.dependencies['@coded-fit/shared']='file:./shared';p.scripts.typecheck='tsc --noEmit';return JSON.stringify(p,null,2)});
edit('frontend/tsconfig.json',s=>s.replace('../shared/src','./shared/src'));
edit('frontend/package-lock.json',s=>s.replaceAll('file:../shared','file:./shared').replaceAll('"../shared"','"shared"'));
edit('backend/package.json',s=>{const p=JSON.parse(s);p.scripts.test='node --test tests/*.test.js';return JSON.stringify(p,null,2)});
edit('backend/app.js',s=>s.replace("origin: '*'", "origin: (process.env.CLIENT_URL || 'http://localhost:3000').split(',')").replace(/\/\/ Serve frontend static files[\s\S]*?\/\/ Centralized error handler/, "app.use('/api', (req, res) => res.status(404).json({ success: false, message: 'API route not found' }));\n\n// Centralized error handler"));
edit('backend/routes/orderRoutes.js',s=>s.replace("router.post('/', optionalAuth", "router.post('/', protect").replace("router.get('/:orderNumber', orderController", "router.get('/:orderNumber', protect, orderController").replace("optionalAuth, orderController.submitFitFeedback", "protect, orderController.submitFitFeedback"));
edit('backend/routes/paymentRoutes.js',s=>s.replace("const router = express.Router();", "const router = express.Router();\nrouter.use(require('../middleware/auth').protect);"));
edit('backend/controllers/orderController.js',s=>s.replace("if (!items || items.length === 0)", "if (!Array.isArray(items) || items.length === 0 || items.length > 50)").replace(/    for \(const item of items\) \{[\s\S]*?\n    const shipping =/,`    for (const item of items) {
      const id = item.product || item.productId;
      const p = /^[a-f0-9]{24}$/i.test(id || '') ? await Product.findById(id) : await Product.findOne({ slug: item.slug || id });
      if (!p || p.status !== 'active') return res.status(400).json({ success: false, message: 'Product unavailable. Refresh the catalog.' });
      if (!Number.isInteger(item.qty) || item.qty < 1 || item.qty > 20 || !p.sizes.includes(item.size)) return res.status(400).json({success:false,message:'Invalid quantity or size.'});
      if (item.qty > p.inventory.available) return res.status(409).json({success:false,message:'Insufficient stock.'});
      if (item.customization || item.type === 'made-to-measure') return res.status(422).json({success:false,message:'Custom designs require an approved atelier quote before checkout.'});
      subtotal += p.price * item.qty;
      validatedItems.push({ product:p._id, name:p.name, price:p.price, qty:item.qty, size:item.size, image:p.images[0], type:'ready-to-wear' });
    }

    const shipping =`).replace('subtotal >= 2999 ? 0 : 250','subtotal >= 2999 ? 0 : 150').replace('Math.round(total * 0.05)','0').replace(/`CF\$\{Math.floor\(100000 \+ Math.random\(\) \* 900000\)\}`/g,"`CF-${require('crypto').randomUUID()}`").replace("Order.findOne({ orderNumber: req.params.orderNumber })","Order.findOne({ orderNumber: req.params.orderNumber, userId: req.user._id })").replaceAll('Order.findById(orderId)', 'Order.findOne({ _id: orderId, userId: req.user._id })').replace("{ verifiedByTailor: true, source: 'fit_twin' }","{ source: 'fit_twin' }").replace(/    const newOrder = await Order.create\([\s\S]*?\n    res.status\(201\).json\([\s\S]*?\n    \}\);/, `    req.body = {items: previousOrder.items.map(i => ({product: String(i.product), qty:i.qty, size:i.size})), shippingAddress: previousOrder.shippingAddress};
    return exports.createOrder(req,res,next);`));
edit('backend/routes/v1/index.js',s=>s.replace(/checkoutRouter.post\('\/create-payment-intent',[\s\S]*?\n\}\);/,"checkoutRouter.post('/create-payment-intent', protect, require('../../controllers/paymentController').createPaymentOrder);").replace("productionRouter.get('/tracker/:orderNumber', async", "productionRouter.get('/tracker/:orderNumber', protect, async").replace('Order.findOne({ orderNumber: req.params.orderNumber })','Order.findOne({ orderNumber: req.params.orderNumber, userId: req.user._id })'));
edit('backend/services/providers/otpProvider.js',s=>s.replace('Math.floor(100000 + Math.random() * 900000)',"require('crypto').randomInt(100000, 1000000)").replace(/    \/\/ Allow master dev OTP[\s\S]*?\n    if \(!record\)/,'    if (!record)').replace("return { success: true, message: 'OTP dispatched via SMS gateway' };", "throw Object.assign(new Error('SMS provider integration is not configured. Use email login.'), {statusCode:503});").replace('    // Verify with SMS Gateway\n    return { success: true };',"    throw Object.assign(new Error('SMS verification is unavailable.'), {statusCode:503});").replace('return isConfigured ? new SmsGatewayOtpProvider() : new DevelopmentOtpProvider();',"return isConfigured || process.env.NODE_ENV === 'production' ? new SmsGatewayOtpProvider() : new DevelopmentOtpProvider();"));
edit('frontend/store/cartStore.ts',s=>s.replace("import { create } from 'zustand';","import { create } from 'zustand';\nimport { persist } from 'zustand/middleware';").replace('create<CartStore>((set, get) => ({','create<CartStore>()(persist((set, get) => ({').replace(/\}\)\);\s*$/, "}), {name:'coded-fit-cart-v2', partialize: ({items,totals}) => ({items,totals})}));\n").replace('Math.round(taxable * 0.12)','0').replace('subtotal > 2999','subtotal >= 2999').replace("else if (clean === 'CODEDFIT') percent = 15;",'').replace("`${itemData.customization.fabricId}-${itemData.customization.colorHex}-${itemData.customization.collar}`",'JSON.stringify(itemData.customization)').replace("${itemData.size}_${customKey}","${itemData.size}_${itemData.colorHex}_${customKey}"));
edit('mobile-app/services/api.ts',s=>s.replace("import AsyncStorage", "import { Platform } from 'react-native';\nimport AsyncStorage").replace("const DEFAULT_API_BASE = 'http://localhost:5000/api/v1';", "const DEFAULT_API_BASE = process.env.EXPO_PUBLIC_API_URL || (Platform.OS === 'android' ? 'http://10.0.2.2:5000/api/v1' : 'http://localhost:5000/api/v1');"));
edit('mobile-app/hooks/useAuth.ts',s=>s.replace(/        \/\/ Fallback for simulators[\s\S]*?return true;/,'        return false;'));
