'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,Pause,Play,Ruler,Box,ScanLine} from 'lucide-react';
import {useCatalog} from '@/lib/useCatalog';
import {ProductGrid} from '@/components/ecommerce/ProductGrid';
const edits=[
 {name:'OFF-DUTY',sub:'Oversized. Understated. All you.',href:'/shop?search=oversized',image:'https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=750&q=85',tag:'THE T-SHIRT EDIT'},
 {name:'STREET LEVEL',sub:'Everyday pieces. Main character energy.',href:'/shop?gender=men',image:'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=750&q=85',tag:'MENSWEAR'},
 {name:'NO RULES',sub:'Your style doesn’t need permission.',href:'/shop?gender=women',image:'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=750&q=85',tag:'WOMENSWEAR'}
];
export default function ReferenceHome(){
 const {products,loading,error,retry}=useCatalog();
 const video=useRef<HTMLVideoElement>(null);
 const [playing,setPlaying]=useState(false),[videoError,setVideoError]=useState(false),[edit,setEdit]=useState('All');
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{if(media.matches)video.current?.pause();else video.current?.play().catch(()=>{});};sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
 const selected=products.filter(p=>edit==='All'||p.category===edit).sort((a,b)=>Number(a.slug.startsWith('cf-studio-'))-Number(b.slug.startsWith('cf-studio-'))).slice(0,4);
 return <div className="cf-home">
 <section className="cf-campaign" aria-labelledby="campaign-title">
  <div className="cf-campaign-copy"><p className="cf-eyebrow"><span className="cf-live-dot"/> INDEPENDENT STYLE. INDIVIDUAL FIT.</p><h1 id="campaign-title">WEAR<br/>YOUR<br/><span>OWN CODE.</span></h1><p className="cf-campaign-description">For the ones who never fit the template.<br/>Streetwear essentials. A fit that’s yours.</p><div className="cf-actions"><Link href="/shop" className="cf-cta cf-cta-red">SHOP THE COLLECTION <ArrowUpRight size={20}/></Link><Link href="/studio" className="cf-text-link">MAKE IT YOURS <ArrowUpRight size={17}/></Link></div><div className="cf-campaign-bottom"><span>EST. FOR THE EVERYDAY ORIGINALS</span><a href="#the-edit" aria-label="Explore the collection below"><ArrowDown size={19}/></a></div></div>
  <div className="cf-campaign-film"><div className="cf-film-fallback" aria-hidden="true"><img src="/brand/coded-fit-logo.png" alt="" className="w-4/5"/><p>UNIFORM FOR<br/>THE UNORDINARY.</p></div>{!videoError&&<video ref={video} muted loop playsInline preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>setVideoError(true)} aria-label="Monochrome fashion editorial film" src="/images/coded-fit-campaign.mp4"/>}<div className="cf-film-shade"/><div className="cf-film-top"><span>THE EVERYDAY / RECODED</span><span>CF / 01</span></div><div className="cf-film-caption"><span>LESS ORDINARY.<br/><b>MORE YOU.</b></span>{!videoError&&<button className="cf-film-control" aria-label={playing?'Pause campaign film':'Play campaign film'} onClick={()=>{if(playing)video.current?.pause();else video.current?.play().catch(()=>setVideoError(true));}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button>}</div></div>
 </section>
 <div className="cf-ticker" aria-label="Style without limits"><div aria-hidden="true">{Array.from({length:4},(_,i)=><span key={i}>YOUR FIT. YOUR RULES. <b>✳</b> NEVER DEFAULT. <b>✳</b> ALWAYS ORIGINAL. <b>✳</b></span>)}</div></div>
 <section className="cf-section" id="the-edit"><div className="cf-section-title"><div><p className="cf-eyebrow">01 / FIND YOUR FREQUENCY</p><h2>PICK YOUR <span>PERSONALITY.</span></h2></div><Link href="/shop" className="cf-underlink">SHOP ALL <ArrowUpRight size={17}/></Link></div><div className="cf-edit-grid">{edits.map((item,i)=><Link href={item.href} key={item.name} className="cf-edit-card"><img src={item.image} alt={item.tag} loading="lazy" onError={e=>{e.currentTarget.src='/images/placeholder.svg';}}/><span className="cf-edit-tag">{item.tag}</span><div className="cf-edit-copy"><small>0{i+1} / THE CODED FIT EDIT</small><h3>{item.name}</h3><p>{item.sub}</p></div><span className="cf-round-arrow"><ArrowUpRight size={23}/></span></Link>)}</div></section>
 <section className="cf-section cf-rotation"><div className="cf-section-title"><div><p className="cf-eyebrow">02 / GOOD FITS ON REPEAT</p><h2>YOUR NEXT <span>ROTATION.</span></h2></div><Link href="/shop" className="cf-underlink">VIEW COLLECTION <ArrowUpRight size={17}/></Link></div><div className="cf-edit-tabs" aria-label="Filter featured collection">{['All','T-Shirts','Shirts','Bottoms','Hoodies'].map(label=><button key={label} onClick={()=>setEdit(label)} aria-pressed={edit===label} className={edit===label?'active':''}>{label==='All'?'All pieces':label}</button>)}</div>{loading?<div className="cf-skeletons" role="status" aria-label="Loading collection">{[1,2,3,4].map(n=><div key={n}/>)}</div>:error?<div className="cf-catalog-message" role="alert"><h3>THE DROP WILL BE RIGHT BACK.</h3><p>We couldn’t connect to the collection. Give it another try.</p><button className="cf-cta cf-cta-black" onClick={retry}>RELOAD COLLECTION</button></div>:<ProductGrid products={selected} columns={4}/>}</section>
 <section className="cf-lab"><div className="cf-lab-art" aria-hidden="true"><div className="cf-orbit cf-orbit-one"/><div className="cf-orbit cf-orbit-two"/><div className="cf-lab-object"><img src="/brand/coded-fit-logo.png" alt=""/><small>BUILT AROUND YOU</small></div><span className="cf-coordinate">X / YOUR STYLE<br/>Y / YOUR FIT<br/>Z / YOUR RULES</span><span className="cf-lab-index">[ PERSONAL STYLE LAB ]</span></div><div className="cf-lab-copy"><p className="cf-eyebrow">03 / YOU ARE THE BLUEPRINT</p><h2>DON’T JUST<br/>WEAR IT.<br/><span>CREATE IT.</span></h2><p>A wardrobe with your name on it. Explore silhouettes, play with colour, and build your own look in our interactive 3D studio.</p><Link href="/studio" className="cf-cta cf-cta-red">ENTER THE 3D STUDIO <ArrowUpRight size={20}/></Link><div className="cf-lab-steps"><span>01 CHOOSE</span><span>02 CUSTOMIZE</span><span>03 SAVE YOUR LOOK</span></div></div></section>
 <section className="cf-section cf-fit-tools"><div className="cf-section-title"><div><p className="cf-eyebrow">MORE THAN A GOOD LOOK</p><h2>MAKE IT <span>PERSONAL.</span></h2></div></div><div className="cf-tools-grid">{[{Icon:Ruler,name:'Find your fit.',body:'Save your measurements and preferred silhouette in one personal profile.',href:'/visualizer',cta:'BUILD YOUR PROFILE'},{Icon:ScanLine,name:'Picture your look.',body:'Explore photo try-on for a visual preview of your next outfit.',href:'/try-on',cta:'EXPLORE TRY-ON'},{Icon:Box,name:'Keep it together.',body:'Your orders, saved pieces and delivery details. All in your account.',href:'/account',cta:'YOUR ACCOUNT'}].map(({Icon,name,body,href,cta})=><Link href={href} key={name}><Icon size={26}/><h3>{name}</h3><p>{body}</p><span>{cta}<ArrowUpRight size={16}/></span></Link>)}</div></section>
 <section className="cf-manifesto"><p className="cf-eyebrow">NO DRESS CODE. JUST CODED FIT.</p><h2>FIT IN?<br/><span>NAH. STAND OUT.</span></h2><Link href="/shop" className="cf-cta cf-cta-white">FIND YOUR NEXT FIT <ArrowUpRight size={20}/></Link></section>
 </div>;
}

