'use client';
import Link from 'next/link';
import {useCatalog} from '@/lib/useCatalog';
import {ProductGrid} from '@/components/ecommerce/ProductGrid';
export default function StoreHome(){const {products,error,loading}=useCatalog();return <div>
  <section className="relative min-h-[78vh] bg-neutral-950 text-white flex items-end overflow-hidden">
    <video autoPlay muted loop playsInline className="absolute inset-0 w-full h-full object-cover opacity-50" src="/images/fashion-hero.mp4" />
    <div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent" />
    <div className="relative w-full max-w-7xl mx-auto px-6 py-16 md:py-24"><p className="text-xs tracking-[.35em] mb-6">CODED FIT / BUILT AROUND YOU</p><h1 className="text-6xl md:text-8xl font-black tracking-tighter max-w-3xl leading-[.95]">Wear your<br /><span className="text-red-500">own code.</span></h1><p className="max-w-md text-stone-300 mt-7 leading-relaxed">Find your everyday essentials. Build a character, make an outfit, and explore your fit in the studio.</p><div className="flex flex-wrap gap-3 mt-8"><Link href="/shop" className="bg-white text-black px-7 py-4 rounded-lg font-bold">Shop the collection ↗</Link><Link href="/studio" className="border border-white/50 px-7 py-4 rounded-lg">Enter character lab</Link></div></div>
  </section>
  <div className="border-b bg-white"><div className="max-w-7xl mx-auto px-6 py-5 flex flex-wrap justify-between gap-4 text-xs tracking-widest"><span>01 / FIND YOUR PIECE</span><span>02 / MAKE IT YOURS</span><span>03 / BUILD YOUR LOOK</span></div></div>
  <section className="max-w-7xl mx-auto px-6 py-16"><div className="flex justify-between items-end mb-8"><div><p className="text-xs tracking-widest text-stone-500">THE EVERYDAY EDIT</p><h2 className="text-4xl font-bold mt-2 tracking-tight">Your next rotation.</h2></div><Link href="/shop" className="text-sm underline">View all</Link></div>{loading && <p>Loading collection…</p>}{error && <p role="alert">The catalog is temporarily unavailable. Please try again.</p>}<ProductGrid products={products.slice(0,4)} columns={4} /></section>
  <section className="max-w-7xl mx-auto px-6 pb-16 grid md:grid-cols-2 gap-5">{[{n:'01',title:'Create your character.',body:'Adjust measurements, switch poses and build outfits in an interactive 3D wardrobe.',href:'/studio',cta:'Open the studio'},{n:'02',title:'See it on your photo.',body:'Select a garment and use the configured AI try-on provider. Generated previews are a visual guide, not a fit guarantee.',href:'/try-on',cta:'Explore photo try-on'}].map(x=><Link key={x.n} href={x.href} className="group rounded-2xl p-8 md:p-12 bg-stone-200 hover:bg-stone-300 transition-colors"><span className="text-sm text-stone-500">CF / {x.n}</span><h2 className="text-3xl font-bold mt-12">{x.title}</h2><p className="max-w-sm text-stone-600 mt-4 leading-relaxed">{x.body}</p><p className="mt-8 font-bold">{x.cta} ↗</p></Link>)}</section>
  </div>;}
