require('dotenv').config();
const {test}=require('node:test');
const assert=require('node:assert/strict');
const mongoose=require('mongoose');
const crypto=require('crypto');

test('commerce API: real auth, authoritative pricing, ownership and payment binding',async t=>{
  const dbName='coded_fit_verification_'+crypto.randomBytes(6).toString('hex');
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/coded_fit',{dbName,serverSelectionTimeoutMS:5000});
  const app=require('../app');
  const server=app.listen(0);
  await new Promise(resolve=>server.once('listening',resolve));
  const base=`http://127.0.0.1:${server.address().port}/api/v1`;
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));if(mongoose.connection.name===dbName && dbName.startsWith('coded_fit_verification_'))await mongoose.connection.dropDatabase();await mongoose.disconnect();});
  const call=async(path,body,token,method=body?'POST':'GET')=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};};
  const registered=await call('/auth/register',{name:'Test buyer',email:'buyer@example.test',password:'Long-test-password-2026'});
  assert.equal(registered.status,201);
  const token=registered.data.token;
  const other=await call('/auth/register',{name:'Other buyer',email:'other@example.test',password:'Long-test-password-2026'});
  assert.equal((await call('/auth/login',{email:'buyer@example.test',password:'incorrect'})).status,401);
  const Product=require('../models/Product');
  const product=await Product.create({name:'Verification Tee',slug:'verification-tee',description:'Test fixture',category:'T-Shirts',gender:'unisex',price:1200,images:['https://example.test/tee.jpg'],fabric:'Cotton',sizes:['M'],inventory:{stock:5,available:5}});
  const shippingAddress={fullName:'Test Buyer',phone:'9999999999',street:'Test street',city:'Ahmedabad',state:'Gujarat',postalCode:'380001',country:'India'};
  const payload={items:[{productId:String(product._id),qty:1,size:'M',price:1}],shippingAddress,payment:{status:'paid'},totals:{total:1}};
  assert.equal((await call('/orders',payload)).status,401);
  assert.equal((await call('/orders',{...payload,items:[{...payload.items[0],qty:-2}]},token)).status,400);
  const created=await call('/orders',payload,token);
  assert.equal(created.status,201);
  assert.equal(created.data.order.totals.total,1350);
  assert.equal(created.data.order.items[0].price,1200);
  assert.equal(created.data.order.payment.status,'pending');
  const order=created.data.order;
  assert.equal((await call('/orders/'+order.orderNumber,undefined,other.data.token)).status,404);
  assert.equal((await call('/production/tracker/'+order.orderNumber,undefined,other.data.token)).status,404);
  assert.equal((await call('/payments/create-order',{orderId:order._id},other.data.token)).status,404);
  assert.equal((await call('/payments/verify',{orderId:order._id,razorpayOrderId:'order_sim_fake',razorpayPaymentId:'pay_fake',razorpaySignature:'sig_mock_verified'},token)).status,400);
  const gateway=require('../services/securePayment');
  const originalCreate=gateway.createOrder, originalFetch=gateway.fetchPayment;
  const oldSecret=process.env.RAZORPAY_KEY_SECRET;
  process.env.RAZORPAY_KEY_SECRET='isolated-test-secret';
  gateway.createOrder=async({amount})=>({id:'order_test_bound',amount:amount*100,currency:'INR'});
  gateway.fetchPayment=async()=>({order_id:'order_test_bound',amount:135000,currency:'INR',status:'captured'});
  t.after(()=>{gateway.createOrder=originalCreate;gateway.fetchPayment=originalFetch;process.env.RAZORPAY_KEY_SECRET=oldSecret;});
  const intent=await call('/payments/create-order',{orderId:order._id,amount:1},token);
  assert.equal(intent.data.amount,135000);
  const signature=crypto.createHmac('sha256','isolated-test-secret').update('order_test_bound|pay_test').digest('hex');
  const verification={orderId:order._id,razorpayOrderId:'order_test_bound',razorpayPaymentId:'pay_test',razorpaySignature:signature};
  assert.equal((await call('/payments/verify',verification,token)).data.order.payment.status,'paid');
  assert.equal((await call('/payments/verify',verification,token)).status,200);
  assert.equal((await call('/payments/create-order',{orderId:order._id},token)).status,409);
  const Fabric=require('../models/Fabric');
  await Fabric.create({fabricId:'test-cotton',name:'Cotton',origin:'Test',gsm:'240',previewColor:'#ffffff',priceAdd:450,inStock:true});
  const custom=await call('/orders',{...payload,items:[{...payload.items[0],customization:{garmentType:'tshirt',fit:'regular',colorHex:'#ffffff',collar:'spread',cuff:'barrel',button:'horn',fabricId:'test-cotton',fabricPriceAdd:-10000,printLayers:[{id:'custom-print',kind:'text',side:'back',text:'MY CODE',font:'sans-serif',color:'#e5192b',x:50,y:45,scale:50,rotation:0}],printPriceAdd:-9999,monogram:{enabled:true,text:'CF',priceAdd:0}}}]},token);
  assert.equal(custom.status,201);
  assert.equal(custom.data.order.items[0].price,2099);
  assert.equal(custom.data.order.items[0].customization.monogram,'CF');
  assert.equal(custom.data.order.items[0].design.printLayers[0].text,'MY CODE');
  assert.equal(custom.data.order.items[0].design.printLayers[0].side,'back');
  assert.equal(custom.data.order.items[0].design.printPriceAdd,199);
  const Order=require('../models/Order');
  await Order.updateOne({_id:custom.data.order._id},{$set:{'payment.orderId':'order_webhook_test'}});
  const previousWebhook=process.env.RAZORPAY_WEBHOOK_SECRET;
  process.env.RAZORPAY_WEBHOOK_SECRET='isolated-webhook-secret';
  t.after(()=>{if(previousWebhook===undefined)delete process.env.RAZORPAY_WEBHOOK_SECRET;else process.env.RAZORPAY_WEBHOOK_SECRET=previousWebhook;});
  const event=JSON.stringify({event:'payment.captured',payload:{payment:{entity:{id:'pay_webhook_test',order_id:'order_webhook_test',status:'captured',currency:'INR',amount:224900}}}});
  const sendWebhook=signature=>fetch(base+'/payments/webhook',{method:'POST',headers:{'Content-Type':'application/json','x-razorpay-signature':signature},body:event});
  assert.equal((await sendWebhook('forged')).status,400);
  const webhookSignature=crypto.createHmac('sha256','isolated-webhook-secret').update(event).digest('hex');
  assert.equal((await sendWebhook(webhookSignature)).status,200);
  assert.equal((await sendWebhook(webhookSignature)).status,200);
  assert.equal((await Order.findById(custom.data.order._id)).payment.status,'paid');
  const designs=await call('/designs',{configuration:{garmentType:'tshirt'},name:'Saved tee'},token);
  assert.equal(designs.status,201);
  assert.equal((await call('/designs',undefined,other.data.token)).data.designs.length,0);
  assert.equal((await call('/designs',undefined,token)).data.designs.length,1);
  assert.equal((await call('/orders/my-orders',undefined,token)).data.orders.length,2);
  assert.equal((await call('/returns',{orderNumber:order.orderNumber},token)).status,503);
});

