'use client';
import Link from 'next/link';
import {BrandLogo} from './BrandLogo';
import {usePathname,useRouter} from 'next/navigation';
import {useEffect,useState} from 'react';
import {Search,User,ShoppingBag,Menu,X,ArrowUpRight} from 'lucide-react';
import {useCartStore} from '@/store/cartStore';
import {useAuthStore} from '@/store/authStore';
export function ReferenceHeader(){
 const {items,openDrawer}=useCartStore();const {user,openLoginModal}=useAuthStore();
 const [open,setOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState('');const pathname=usePathname(),router=useRouter();
 const links=[['MEN','/shop?gender=men'],['WOMEN','/shop?gender=women'],['ALL PIECES','/shop'],['OVERSIZED','/shop?search=oversized'],['BESPOKE STUDIO','/studio']];
 useEffect(()=>{setOpen(false);setSearchOpen(false);},[pathname]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);setSearchOpen(false);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 return <header className="sticky top-0 z-40 bg-white border-b border-neutral-200"><a href="#main-content" className="cf-skip-link">Skip to content</a><div className="bg-[#111] text-white px-4 py-2 text-center font-mono text-[9px] tracking-widest">YOUR FIT. YOUR RULES. <span className="mx-3 text-red-500">✳</span> FREE SHIPPING ON ORDERS ₹2,999+</div><div className="max-w-[1500px] mx-auto px-4 lg:px-10 flex items-center justify-between gap-4 h-[72px] lg:h-[82px]"><Link href="/" aria-label="CODED FIT home" className="cf-brand-home shrink-0"><BrandLogo/></Link><nav aria-label="Main navigation" className="hidden lg:flex h-full items-center gap-7">{links.map(([label,href])=><Link key={label} href={href} className={`font-headline text-[18px] font-bold hover:text-vermillion ${href==='/studio'?'text-vermillion':''}`}>{label}{href==='/studio'&&<ArrowUpRight className="inline ml-1" size={14}/>}</Link>)}</nav><div className="flex items-center gap-1 sm:gap-3"><button className="p-2" aria-label="Search catalog" aria-expanded={searchOpen} aria-controls="catalog-search" onClick={()=>{setSearchOpen(!searchOpen);setOpen(false);}}><Search size={20}/></button>{user?<Link className="p-2" href="/account" aria-label="My account"><User size={20}/></Link>:<button className="p-2" aria-label="Sign in" onClick={()=>openLoginModal('email')}><User size={20}/></button>}<button aria-label={`Shopping bag, ${items.reduce((n,i)=>n+i.qty,0)} items`} onClick={openDrawer} className="relative p-2"><ShoppingBag size={20}/>{items.length>0&&<span className="absolute right-0 top-0 bg-vermillion text-white rounded-full min-w-4 px-1 text-[9px]">{items.reduce((n,i)=>n+i.qty,0)}</span>}</button><button className="lg:hidden p-2" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>{setOpen(!open);setSearchOpen(false);}}>{open?<X size={22}/>:<Menu size={22}/>}</button></div></div>{searchOpen&&<form id="catalog-search" role="search" className="flex gap-3 border-t p-4 max-w-3xl mx-auto" onSubmit={e=>{e.preventDefault();router.push('/shop?search='+encodeURIComponent(query.trim()));setSearchOpen(false);}}><input autoFocus aria-label="Search clothing" className="border border-neutral-300 p-3 flex-1 min-w-0 text-sm" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try oversized, cotton, black…"/><button className="bg-black text-white px-5 text-xs font-bold">SEARCH</button></form>}{open&&<nav id="mobile-navigation" aria-label="Mobile navigation" className="lg:hidden grid grid-cols-2 border-t p-5 gap-4">{[...links,['SHIRTS','/shop?category=Shirts'],['TROUSERS','/shop?category=Bottoms'],['FIT PROFILE','/visualizer']].map(([label,href])=><Link className="font-headline text-xl py-2" onClick={()=>setOpen(false)} key={label} href={href}>{label}</Link>)}</nav>}</header>;
}


